require_relative '../lib/day07'

describe Day07 do
  input = <<~INPUT
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
  INPUT

  describe ".part1" do
    it "returns the solution to part 1" do
      expect(Day07.part1(input)).to eq(21)
    end
  end

  describe ".part2" do
    it "returns the solution to part 2" do
      expect(Day07.part2(input)).to eq(40)
    end
  end
end
